name: pangenome
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - streamlit>=1.28.0
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scikit-learn>=1.3.0
  - plotly>=5.17.0
  - biopython>=1.81
  - pytorch>=2.0.0
  - pip
  - pip:
    - transformers>=4.34.0
    - umap-learn>=0.5.3
    - kaleido-core>=0.2.1